apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: don361/kubernetes-media-notification:1.0
          envFrom:
            - configMapRef:
                name: notification-configmap
            - secretRef:
                name: notification-secret